// layout.tsx or page.tsx (whichever fits your structure)

import { Metadata } from 'next'; // Import for server-side metadata

// Define metadata for this layout or page
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import RootLayout from './RootLayout';

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <RootLayout>{children}</RootLayout>
  );
}
